sudo : required
language: generic 
services :
    - docker

before_install : 
    - docker build -t deamonslayer/reacttest -f Dockerfile.dev .

script:
    - docker run -e CI=true deamonslayer/reacttest npm run test